import { lessons } from './lesson.js';
export default lessons('foundations', [
  ['computers', 'How Computers Work',
    'A computer executes instructions. The CPU performs calculations, RAM holds active data, and storage retains files after power is removed. Input and output devices connect this work to the outside world.',
    'Separating computation, memory and persistent storage helps explain performance problems and where sensitive data can remain.',
    'Opening a document reads bytes from storage into RAM. The CPU runs the editor. Saving writes the updated bytes back to storage.',
    ['CPU', 'RAM', 'Persistent storage', 'Input/output'],
    { instruction: 'Sketch the path of a document from disk to screen and back. Label which components lose data when powered off.', observation: 'RAM is normally volatile; a saved file persists on storage.' },
    'Where should a document be saved to survive a normal shutdown?', ['RAM only', 'Persistent storage', 'CPU cache'], 1,
    'Persistent storage retains the saved bytes without power; RAM and CPU caches do not.'],
  ['operating-systems', 'Operating Systems',
    'An operating system manages hardware and provides services to applications. Its kernel schedules CPU time, manages memory and enforces access rules. Applications request services through system calls.',
    'Security boundaries depend on OS enforcement. An application should receive only the permissions it needs.',
    'Two programs can run at once because the scheduler shares CPU time. Separate virtual address spaces help isolate their memory.',
    ['Kernel', 'System call', 'Scheduler', 'Isolation'],
    { instruction: 'Inspect your own OS version. Identify the OS and its release; do not publish identifying machine details.', commands: { win32: 'ver (CMD) or [System.Environment]::OSVersion (PowerShell)', linux: 'uname -sr', darwin: 'sw_vers' }, observation: 'The output describes your OS, not the version of every installed application.' },
    'Which component mediates an application request to access hardware?', ['DNS resolver', 'Text editor', 'Operating system'], 2,
    'The OS exposes controlled services instead of letting ordinary applications directly control all hardware.'],
  ['files-processes', 'Files & Processes',
    'A file is named data stored in a filesystem. A process is a running instance of a program with memory, an identifier and an execution context. Multiple processes can run the same program.',
    'A suspicious file and a suspicious running process require different observations. Deleting a filename is not a reliable way to stop a process.',
    'An editor executable is a file. Launching it creates a process. Opening notes.txt makes that process read another file.',
    ['File', 'Process', 'PID', 'Executable'],
    { instruction: 'List processes on your own machine and find the shell you are using. Do not terminate anything.', commands: { win32: 'tasklist', linux: 'ps -e', darwin: 'ps -e' }, observation: 'Each running process has a PID; the same program name can appear multiple times.' },
    'You launch the same program twice. What can differ?', ['The process IDs', 'The meaning of a byte', 'The OS must change'], 0,
    'Each process has its own execution context and PID even when it uses the same executable.'],
  ['command-line', 'The Command Line',
    'A shell reads command text, handles quoting and dispatches built-in commands or programs. A terminal displays the shell. Arguments tell a command what to operate on; paths identify files and directories.',
    'Understanding shell parsing prevents accidental changes. Read commands before running them and quote paths containing spaces.',
    'A terminal is the window; PowerShell or Bash is the shell inside it. Their syntax differs even when they launch the same program.',
    ['Terminal', 'Shell', 'Argument', 'Working directory'],
    { instruction: 'Display your working directory. Then explain why a relative path depends on this location.', commands: { win32: 'cd (CMD) or Get-Location (PowerShell)', linux: 'pwd', darwin: 'pwd' }, observation: 'The displayed directory is the base for relative paths; it is not necessarily your home directory.' },
    'Why quote a path such as "My Notes/file.txt"?', ['To encrypt the file', 'To keep spaces inside one argument', 'To grant administrator access'], 1,
    'Quoting helps the shell treat a path containing spaces as one argument.'],
  ['internet', 'Internet Fundamentals',
    'The Internet connects independently operated networks using common protocols. Packets cross routers to reach destinations. The Web is one application built on this network, alongside email and many other services.',
    'Distinguishing connectivity from application behavior makes troubleshooting systematic: a working network does not guarantee a working website.',
    'A browser may resolve a name, establish a connection, negotiate TLS and request a page. Failure at any step can prevent the page from loading.',
    ['Packet', 'Router', 'Protocol', 'Client/server'],
    { instruction: 'Draw browser -> home router -> provider -> server. Mark which systems you own and which require someone else\'s authorization to test.', observation: 'Being able to reach a server does not grant permission to test its security.' },
    'A website fails while another service works. What follows?', ['The entire Internet is offline', 'All packets are encrypted', 'The failure may be application-specific'], 2,
    'A service can fail independently of the underlying network or other services.'],
  ['logic', 'Programming Logic & Engineering Habits',
    'Programs combine sequence, decisions and repetition. A useful engineering workflow defines expected behavior, builds a small solution, tests assumptions and documents results. Automation should follow understanding.',
    'Security is engineering: clear requirements and reproducible observations are more valuable than blindly running tools.',
    'To check a backup: verify it exists, attempt a restore in an isolated location, compare the restored data and record the result. Existence alone is not proof of recoverability.',
    ['Sequence', 'Condition', 'Loop', 'Evidence'],
    { instruction: 'Write pseudocode for checking three sample backup records. Use invented filenames; include what happens when a record is missing.', observation: 'A branch handles missing data and a loop avoids copying the same logic three times.' },
    'When is it sensible to automate a process?', ['After understanding and testing its steps', 'Before knowing what it changes', 'Only when it uses security tools'], 0,
    'Understand the process, test failure cases, then automate and document it.'],
]);
