import { lessons } from './lesson.js';
export default lessons('linux', [
  ['fundamentals', 'Linux Fundamentals',
    'Linux is a kernel used by many distributions. A distribution combines the kernel, system tools and a package ecosystem. A shell is a separate command interpreter, not the kernel itself.',
    'Commands and service managers vary between distributions. Identify the environment before following instructions.',
    'Two machines can both use Linux while having different package managers and default shells. macOS has Unix tools but does not use the Linux kernel.',
    ['Kernel', 'Distribution', 'Shell', 'User space'],
    { instruction: 'In a Linux VM or an existing WSL environment you own, read the distribution description. On other systems, use the example conceptually; no installation is required.', commands: { linux: 'cat /etc/os-release' }, observation: 'Distribution metadata identifies the user-space environment; it is different from a kernel version.' },
    'Which statement is accurate?', ['Every Linux system has identical tools', 'A Linux distribution combines a kernel with user-space software', 'Bash is the Linux kernel'], 1,
    'Distributions package Linux with different tools, defaults and release policies.'],
  ['filesystem', 'The Filesystem',
    'Linux organizes paths under /. /etc commonly contains configuration, /home user directories, /var changing application data and /tmp temporary files. A relative path starts from the current directory.',
    'Knowing where data belongs prevents accidental exposure and makes operations easier to audit.',
    '/home/learner/notes.txt is absolute. notes.txt is relative. .. refers to a parent directory and can change where a relative path points.',
    ['Root directory', 'Absolute path', 'Relative path', 'Home'],
    { instruction: 'List the root directory in your own Linux environment. Observe names only; do not edit system files.', commands: { linux: 'ls /' }, observation: 'Directories separate configuration, executables and user data; exact layouts vary.' },
    'Which path is absolute on Linux?', ['notes.txt', '../notes.txt', '/home/learner/notes.txt'], 2,
    'A leading / anchors the path at the filesystem root.'],
  ['shell', 'Shell, Quoting & Help',
    'Bash expands variables and patterns before a program receives arguments. Single quotes preserve literal text; double quotes preserve spaces while allowing variable expansion. Built-ins and external programs can share names.',
    'Unquoted input can unexpectedly split into arguments or expand to filenames. Never paste a command without understanding its effects.',
    'printf "%s\\n" "$HOME" prints the home path as one argument. Single-quoting $HOME would print the literal variable name.',
    ['Expansion', 'Quoting', 'Built-in', 'Manual'],
    { instruction: 'In Bash, print text containing a space. Use the help page for printf to inspect its arguments.', commands: { linux: 'printf "%s\\n" "hello systems"', darwin: 'printf "%s\\n" "hello systems"' }, observation: 'The quoted phrase is passed as one argument; nothing is downloaded or changed.' },
    'Why quote a Bash variable used as a filename?', ['To preserve spaces and prevent glob expansion of its value', 'To give root permission', 'To compress the file'], 0,
    'Double quotes prevent word splitting and pathname expansion of the expanded value.'],
  ['users-groups', 'Users & Groups',
    'Processes run with user and group identities. Files have an owner and group, and permissions are checked against these identities. The root account has broad powers; routine work should use an ordinary account.',
    'Identity and least privilege limit the damage a mistake or compromised program can cause.',
    'A team can share a group for reading project files without sharing one password or giving everyone administrative access.',
    ['UID', 'GID', 'Group membership', 'Least privilege'],
    { instruction: 'Display your own identity. Do not change users or elevate privileges.', commands: { linux: 'id', darwin: 'id' }, observation: 'The output shows your user identifier and groups. Group membership affects access checks.' },
    'What is a good default for routine development?', ['Run everything as root', 'Use an ordinary account with necessary permissions', 'Share an administrator password'], 1,
    'Use only the privileges needed; administrative accounts expand the consequences of mistakes.'],
  ['permissions', 'File & Directory Permissions',
    'Unix permissions grant read, write and execute to owner, group and others. For a directory, execute permits traversal and read permits listing names. Directory write permission affects creating and removing entries.',
    'File content protection and directory entry protection are different. Broad modes such as 777 usually exceed the requirement.',
    'Mode 640 means owner read/write, group read, others no access. A directory often also needs execute permission to access files inside it.',
    ['rwx', 'Owner/group/others', 'Traversal', 'Octal mode'],
    { instruction: 'Inspect permissions on your own home directory. Decode the bits without changing them.', commands: { linux: 'ls -ld "$HOME"', darwin: 'ls -ld "$HOME"' }, observation: 'The initial d indicates a directory; the next nine characters describe three sets of access bits.' },
    'What does directory execute permission normally allow?', ['Running every file as root', 'Decrypting all files', 'Traversing the directory'], 2,
    'Directory execute permission permits path traversal; it is not permission to execute every file within it.'],
  ['processes-services', 'Processes & Services',
    'A process is a running program. A service is a long-running function often supervised by a service manager. Many Linux distributions use systemd, but containers and other distributions may not.',
    'A service configuration and its current process state can disagree. Inspect before restarting or changing anything.',
    'A service may be enabled for startup yet currently stopped. A running process may also have been started manually.',
    ['PID', 'Service manager', 'Startup', 'Runtime state'],
    { instruction: 'Inspect processes in your own Linux environment. No signals or restarts are needed.', commands: { linux: 'ps -ef', darwin: 'ps -ef' }, observation: 'The process list is a snapshot; it does not prove that a service will start after reboot.' },
    'Does enabled at boot always mean running now?', ['No, startup policy and current state differ', 'Yes, always', 'Only for text editors'], 0,
    'Enabled and active are separate properties; a service can stop or fail after startup.'],
  ['packages', 'Packages & Software Sources',
    'Package managers install and track software from configured sources. Repositories provide metadata and often signature verification. Different distributions use different package formats and commands.',
    'Trusted sources and updates reduce supply-chain risk, but a signature alone does not establish that software is bug-free.',
    'Debian-family systems commonly use apt; Fedora-family systems use dnf. Piping an unknown download into a shell bypasses careful review.',
    ['Repository', 'Package', 'Signature', 'Update'],
    { instruction: 'Make a checklist for evaluating a fictional package: source, maintainer, permissions, dependencies and update policy. Do not install anything.', observation: 'Review includes both authenticity and whether the software is appropriate for the task.' },
    'What is preferable to running an unknown remote installation script?', ['Disable signature checking', 'Run it as root first', 'Review a trusted package source and its requirements'], 2,
    'Use reviewed sources and understand the requested changes before installing software.'],
  ['environment', 'Environment Variables & Secrets',
    'Environment variables are strings passed to processes. Shell variables are not necessarily exported. PATH influences executable lookup; other variables configure applications.',
    'Environment values can reach child processes or diagnostics. They are not a password vault, and dumping the entire environment can expose secrets.',
    'A malicious directory early in PATH could cause a different executable to run than expected. Check the source of tools used in sensitive workflows.',
    ['Environment', 'Export', 'PATH', 'Inheritance'],
    { instruction: 'Print only your shell\'s home path. Avoid commands that dump all environment variables.', commands: { linux: 'printf "%s\\n" "$HOME"', darwin: 'printf "%s\\n" "$HOME"' }, observation: 'This reads one value; do not paste personal paths or credentials into public reports.' },
    'Why avoid sharing a full environment dump?', ['It always crashes the shell', 'It may include credentials or private configuration', 'It changes file permissions'], 1,
    'Environment variables sometimes hold tokens and other sensitive configuration.'],
  ['pipes-text', 'Pipes, Redirection & Text Tools',
    'A pipe sends one program\'s standard output to another\'s standard input. > writes output to a file and normally truncates it; >> appends. grep selects matching lines, while sed and awk transform or summarize text.',
    'Small tools compose well, but output redirection can overwrite valuable files. Start with synthetic data and visible output.',
    'printf "ok\\nerror\\n" | grep error selects only the matching line. It does not need a log file or modify one.',
    ['stdin', 'stdout', 'stderr', 'Pipe', 'Redirection'],
    { instruction: 'Filter synthetic data in Bash; no file redirection is needed.', commands: { linux: 'printf "ok\\nerror\\n" | grep error', darwin: 'printf "ok\\nerror\\n" | grep error' }, observation: 'Only error is printed. Standard error is a different stream unless explicitly redirected.' },
    'What does > usually do to an existing output file?', ['Always appends', 'Encrypts it', 'Truncates it before writing'], 2,
    'The > operator can replace existing content. Understand the destination before using it.'],
  ['ssh-logs', 'SSH, Networking & Logs',
    'SSH authenticates a remote endpoint and user over an encrypted connection. Host keys identify servers. Logs provide evidence of events but may contain sensitive data and can be incomplete.',
    'Unexpected host-key changes deserve investigation. Sharing raw logs can leak tokens, names or internal addresses.',
    'A rebuilt authorized lab VM may have a new host key. Verify the new fingerprint through a trusted channel before updating trust.',
    ['SSH', 'Host key', 'Fingerprint', 'Log event'],
    { instruction: 'Analyze this synthetic log: "2026-01-01T12:00:00Z auth denied user=demo". Separate timestamp, subsystem, outcome and identity. Do not connect to remote hosts.', observation: 'One failed authentication event is evidence of a failure, not enough evidence to identify an attacker.' },
    'What is the best response to an unexpected SSH host-key change?', ['Verify the fingerprint through a trusted channel', 'Ignore all future host-key checks', 'Publish your private key'], 0,
    'A changed host key may be legitimate or signal a problem; independent verification preserves endpoint trust.'],
  ['bash', 'Bash Basics & Safe Scripts',
    'Bash scripts combine commands, variables, conditions and loops. Check exit statuses and quote expansions. Scripts should document inputs and effects and stop safely when required steps fail.',
    'Automation magnifies both correct reasoning and mistakes. Use synthetic inputs and avoid privileged execution while learning.',
    'for name in alpha beta; do printf "%s\\n" "$name"; done prints two known values without touching files.',
    ['Loop', 'Exit status', 'Quoting', 'Failure handling'],
    { instruction: 'Run the read-only loop in Bash on Linux, macOS or your existing authorized Bash environment.', commands: { linux: 'for name in alpha beta; do printf "%s\\n" "$name"; done', darwin: 'for name in alpha beta; do printf "%s\\n" "$name"; done' }, observation: 'Each iteration prints one value. PowerShell and CMD require different syntax; do not paste Bash into them.' },
    'Why test a script with synthetic inputs first?', ['To avoid understanding it', 'To observe behavior before risking real data', 'To grant it extra privileges'], 1,
    'Synthetic inputs let you examine normal and failure behavior in a controlled setting.'],
]);
