import { lessons } from './lesson.js';
export default lessons('networking', [
  ['networks', 'Networks, LAN & WAN',
    'A network connects devices so they can exchange data using agreed protocols. A LAN covers a local environment; a WAN connects networks over broader distances. Ownership and trust are separate from physical distance.',
    'Network boundaries help you locate faults and decide where access controls belong.',
    'A home laptop and printer may share a LAN. An ISP links that LAN to other networks through a router.',
    ['LAN', 'WAN', 'Switch', 'Router'],
    { instruction: 'Draw an imaginary office LAN with two laptops, a switch and a router. Mark its exit to the WAN.', observation: 'Local traffic can stay within the LAN; off-network traffic needs a route.' },
    'Which device commonly forwards traffic between IP networks?', ['Keyboard', 'Router', 'RAM'], 1,
    'Routers choose where to forward packets between IP networks.'],
  ['ip-addresses', 'IP Addresses & Interfaces',
    'An IP address identifies a network interface within a routing context. A device can have several interfaces and addresses. Loopback addresses refer back to the same host.',
    'An address is a routing identifier, not proof of a person\'s identity or permission to access a service.',
    '127.0.0.1 and ::1 are loopback addresses. A service listening only on loopback is normally reachable from the same host.',
    ['Interface', 'Address', 'Loopback', 'Private network'],
    { instruction: 'Inspect your own interfaces without changing them. Find loopback and the active network interface. Keep private details local.', commands: { win32: 'ipconfig', linux: 'ip addr', darwin: 'ifconfig' }, observation: 'Different interfaces can have different addresses; an address alone does not identify a user.' },
    'Where does a packet addressed to 127.0.0.1 go?', ['Every Internet host', 'The DNS root', 'The local host'], 2,
    '127.0.0.1 belongs to the IPv4 loopback range and refers to this host.'],
  ['ipv4-ipv6', 'IPv4 & IPv6',
    'IPv4 uses 32-bit addresses typically written as four decimal octets. IPv6 uses 128-bit addresses written in hexadecimal groups. IPv6 can compress consecutive zero groups once using ::.',
    'Modern networks often support both families. A service can work over one family while the other is misconfigured.',
    '192.0.2.10 and 2001:db8::10 are documentation addresses. They illustrate syntax and should not be used as public test targets.',
    ['32-bit', '128-bit', 'Dual stack', 'Address family'],
    { instruction: 'Expand 2001:db8::10 on paper to eight groups. Compare it with the four octets in 192.0.2.10.', observation: 'The expanded form is 2001:0db8:0000:0000:0000:0000:0000:0010.' },
    'What is a practical consequence of dual stack?', ['IPv6 automatically encrypts applications', 'IPv4 and IPv6 connectivity may need separate checks', 'DNS is no longer needed'], 1,
    'Dual stack supports two protocol families; routing and service configuration can differ.'],
  ['subnetting', 'Subnets & CIDR',
    'A CIDR prefix specifies how many leading address bits describe a network. In IPv4, /24 leaves eight bits for addresses within that block. Routing compares destination addresses with prefixes.',
    'Prefixes define network scope. An overly broad rule may grant access to many more addresses than intended.',
    '192.0.2.0/24 spans 192.0.2.0 through 192.0.2.255. In a conventional IPv4 LAN, the first and last addresses are reserved for network and broadcast.',
    ['Prefix', 'Network bits', 'Host bits', 'CIDR'],
    { instruction: 'Decide whether 192.0.2.42 and 192.0.3.42 belong to 192.0.2.0/24. Use only this paper exercise.', observation: 'The first address matches the first 24 bits; the second does not.' },
    'Which IPv4 block contains more addresses?', ['/28', '/24', 'Both contain the same count'], 1,
    'A /24 leaves eight host bits (256 addresses); a /28 leaves four (16 addresses).'],
  ['mac-arp', 'MAC Addresses & ARP',
    'Ethernet uses link-layer MAC addresses to deliver frames locally. ARP resolves an IPv4 address to a link-layer address on the local network. IPv6 uses Neighbor Discovery instead of ARP.',
    'Local delivery and end-to-end routing are different layers. ARP entries are not strong evidence of identity.',
    'To reach a remote IPv4 server, a host commonly resolves the MAC of its local gateway, not the remote server\'s MAC.',
    ['Ethernet', 'Frame', 'MAC', 'ARP cache'],
    { instruction: 'Read the neighbor cache on your machine; do not modify it. An empty cache is normal on some interfaces.', commands: { win32: 'arp -a', linux: 'ip neigh', darwin: 'arp -a' }, observation: 'Entries describe local neighbors and may expire. They are not a map of the Internet.' },
    'For an off-subnet destination, whose MAC is usually needed locally?', ['The local gateway\'s', 'The remote browser\'s', 'Every router on the Internet'], 0,
    'The first frame is delivered to a local next hop, commonly the gateway.'],
  ['tcp-udp', 'TCP vs UDP',
    'TCP provides a connection-oriented ordered byte stream with retransmission and flow control. UDP sends datagrams without built-in delivery or ordering guarantees. Applications can build additional behavior on UDP.',
    'Protocol choice affects latency, failure handling and debugging. TCP reliability does not provide application authentication or encryption.',
    'A file transfer needs every byte in order. A real-time stream may prefer timely updates over waiting for an old packet.',
    ['Connection', 'Byte stream', 'Datagram', 'Retransmission'],
    { instruction: 'Model three numbered messages on paper. Drop message two and compare waiting for retransmission with continuing immediately.', observation: 'Different applications make different tradeoffs between timeliness and completeness.' },
    'Which service is built into TCP?', ['Encryption of all data', 'Ordered byte delivery', 'User authentication'], 1,
    'TCP provides ordering and retransmission, while encryption and identity need other mechanisms.'],
  ['ports', 'Ports & Listening Services',
    'Transport ports distinguish endpoints on a host. A server listens on an address and port; clients commonly use temporary source ports. TCP and UDP have separate port spaces.',
    'Listening on all interfaces can expose a service beyond the local machine. A port number suggests convention, not guaranteed software identity.',
    '127.0.0.1:8080 binds an IPv4 service to loopback. 0.0.0.0:8080 commonly means all local IPv4 interfaces.',
    ['Source port', 'Destination port', 'Listener', 'Bind address'],
    { instruction: 'Inspect local listeners only. Do not scan other machines. Some process details require privileges; skip them.', commands: { win32: 'netstat -an', linux: 'ss -lntu', darwin: 'netstat -an' }, observation: 'Compare loopback listeners with wildcard listeners; visibility does not mean access is authorized.' },
    'Which bind address normally limits IPv4 access to this host?', ['0.0.0.0', 'A public interface', '127.0.0.1'], 2,
    'Loopback keeps ordinary direct connections on the same host.'],
  ['dns', 'DNS',
    'DNS maps domain names to records through resolvers and authoritative servers. A records hold IPv4 addresses, AAAA records hold IPv6 addresses and CNAME records point to another name. Caches retain answers for a limited time.',
    'DNS failures can look like connection failures. Name resolution itself does not prove that an application or website is trustworthy.',
    'In a fictional zone, app.example -> CNAME service.example -> A 192.0.2.10. A TTL tells a cache how long it may retain the answer.',
    ['Resolver', 'Authoritative server', 'A', 'AAAA', 'CNAME', 'TTL'],
    { instruction: 'Trace the fictional records in the example offline. If you run your own DNS lab, query only that lab with nslookup <your-lab-name>.', observation: 'A CNAME contains a name; an A record contains an IPv4 address. Cached answers may remain until their TTL expires.' },
    'What is a main purpose of DNS?', ['Encrypt files', 'Resolve names into records such as addresses', 'Install packages'], 1,
    'DNS retrieves records associated with names, including the addresses clients use to connect.'],
  ['dhcp', 'DHCP',
    'DHCP can lease IPv4 network configuration to clients, including an address, subnet information, gateway and DNS servers. Leases expire and can be renewed. Static configuration is another option.',
    'A valid address alone does not guarantee a correct gateway or DNS configuration.',
    'A laptop joins a lab LAN and receives a lease for a private address. After renewal, the lease may retain the same address.',
    ['Lease', 'DHCP server', 'Gateway', 'Configuration'],
    { instruction: 'Write a fictional lease containing an address, prefix, gateway, DNS server and expiry. Explain each field; do not renew or release your real connection.', observation: 'A lease includes more than an address, and expiry is not the same as deleting the device.' },
    'What does a DHCP lease represent?', ['Permanent ownership of an Internet identity', 'An encrypted website session', 'Time-limited network configuration'], 2,
    'DHCP leases configuration for a period; clients normally attempt to renew it.'],
  ['http-https', 'HTTP & HTTPS',
    'HTTP describes requests and responses: methods, targets, headers, status codes and optional bodies. HTTPS carries HTTP through TLS. A successful connection can still return an application error.',
    'Reading the response separates network success from application behavior. HTTPS protects transport, not every aspect of application security.',
    'GET /notes HTTP/1.1 followed by a Host header requests a resource. A 404 response means the server did not find the requested resource.',
    ['Method', 'Header', 'Status', 'Body', 'TLS'],
    { instruction: 'Write a fictional GET request and a 404 response on paper. Identify which side sends each and where headers end.', observation: 'The server answered even though the requested resource was not found.' },
    'A server returns HTTP 404. What does this establish?', ['An HTTP response was received', 'No network connection was possible', 'TLS always failed'], 0,
    '404 is an application response, not evidence that the server could not be reached.'],
  ['tls', 'TLS & Certificates',
    'TLS protects data in transit with encryption and integrity checks. In typical HTTPS, certificates help the client authenticate the server name through a trusted certificate chain. Validation also checks names and validity periods.',
    'Ignoring certificate errors removes an important identity check. TLS does not prevent unsafe server logic or compromised endpoints.',
    'A certificate valid for one hostname is not automatically valid for another. Encryption without checking the intended peer can still connect you to the wrong system.',
    ['Encryption', 'Integrity', 'Certificate', 'Trust chain'],
    { instruction: 'Review a fictional certificate with subject lab.example and an expired validity date. List why a client should reject it for other.example.', observation: 'Both a hostname mismatch and an expired certificate can invalidate the connection.' },
    'What should you do when a normal service shows an unexpected certificate error?', ['Disable validation permanently', 'Investigate the cause before continuing', 'Assume encryption proves identity'], 1,
    'Investigate the mismatch or trust problem instead of suppressing the protection.'],
  ['routing-nat', 'Routing & NAT',
    'A routing table selects a next hop, normally using the longest matching destination prefix. A default route handles destinations without a more specific match. NAT rewrites addresses and often ports at a boundary.',
    'NAT is not a substitute for explicit firewall policy. Route choice explains where packets go before you troubleshoot the application.',
    'A packet matching both 0.0.0.0/0 and 192.0.2.0/24 uses the more specific /24 route under normal longest-prefix selection.',
    ['Next hop', 'Default route', 'Longest prefix', 'NAT'],
    { instruction: 'Read your own routing table without changing routes.', commands: { win32: 'route print', linux: 'ip route', darwin: 'netstat -rn' }, observation: 'Find the default route and a connected subnet. Multiple routes may coexist.' },
    'Which matching prefix is more specific?', ['/0', '/8', '/24'], 2,
    'The /24 fixes more leading bits, so it describes a narrower destination set.'],
  ['firewalls-vpn', 'Firewalls & VPNs',
    'A firewall allows or denies traffic according to policy and may track connection state. A VPN carries traffic through an authenticated encrypted tunnel. The tunnel endpoint and routing determine which traffic it protects.',
    'A VPN does not make every destination safe. Firewall rules should describe a justified need with the smallest reasonable scope.',
    'A lab service needs access from one trusted subnet. Allowing the whole Internet is a broader policy than the requirement.',
    ['Policy', 'Stateful filtering', 'Tunnel', 'Least privilege'],
    { instruction: 'Design a paper rule allowing a fictional lab subnet to one service. Include source, destination, protocol, port and justification. Do not modify your firewall.', observation: 'A precise rule is easier to review and remove than an undocumented broad exception.' },
    'Does a VPN guarantee that a downloaded file is safe?', ['Yes, all content is inspected', 'No, transport protection is different from content safety', 'Yes, if the icon is blue'], 1,
    'A protected tunnel does not establish that every application or file is trustworthy.'],
  ['network-models', 'OSI, TCP/IP & Troubleshooting',
    'Layered models separate responsibilities. The TCP/IP view groups link, Internet, transport and application functions. The OSI model uses seven conceptual layers. Real implementations do not always fit perfectly into one box.',
    'Troubleshooting by layer avoids random tool use: inspect local configuration, routes, transport and then application responses.',
    'Ethernet carries a frame containing an IP packet containing a TCP segment carrying application bytes. Each layer has its own addressing or control information.',
    ['Encapsulation', 'Link', 'Internet layer', 'Transport', 'Application'],
    { instruction: 'Test only your own loopback interface. Windows uses -n; Unix uses -c to bound the number of probes.', commands: { win32: 'ping -n 2 127.0.0.1', linux: 'ping -c 2 127.0.0.1', darwin: 'ping -c 2 127.0.0.1' }, observation: 'A loopback reply tests part of the local IP stack, not Internet reachability or an HTTP service. Missing ping may simply mean the tool is absent.' },
    'Loopback ping succeeds. What can you conclude?', ['Every website works', 'DNS records are correct', 'The local host answered ICMP loopback probes'], 2,
    'Each test has a limited scope; loopback ICMP success does not validate external routes or applications.'],
]);
