import { lessons } from './lesson.js';
export default lessons('programming', [
  ['variables-types', 'Variables & Data Types',
    'Variables name values. Numbers, strings, booleans and collections represent different kinds of data. Python and JavaScript enforce type rules at runtime; TypeScript adds compile-time checks for JavaScript.',
    'Confusing text with numbers can change program behavior. External input must be validated at runtime even in a typed program.',
    'In JavaScript, "2" + 3 produces "23", while 2 + 3 produces 5. Conversion should be deliberate and checked.',
    ['String', 'Number', 'Boolean', 'Runtime validation'],
    { instruction: 'Use Node.js, already required by this CLI, to compare a number and text.', commands: { all: 'node -p "typeof 42"' }, observation: 'The result is number. Quoted input and parsed JSON may have a different runtime type.' },
    'Does TypeScript make untrusted JSON valid at runtime?', ['Yes, automatically', 'Only on Windows', 'No, runtime validation is still required'], 2,
    'Types are not a runtime boundary for data arriving from files, users or APIs.'],
  ['conditions-loops', 'Conditions & Loops',
    'Conditions select a branch based on a boolean result. Loops repeat work over a collection or until a condition changes. Bound repetition so malformed input cannot cause unlimited work.',
    'Explicit branches make edge cases visible. Bounded loops avoid hanging on missing or hostile input.',
    'Python: for status in [200, 404]: print(status >= 400). JavaScript: [200, 404].map(status => status >= 400). Both classify two responses.',
    ['if', 'Boolean expression', 'Iteration', 'Bound'],
    { instruction: 'Predict the result, then run the local expression.', commands: { all: 'node -p "[200,404].map(status => status >= 400)"' }, observation: 'The first result is false and the second is true. No HTTP requests are sent.' },
    'What is useful when retrying an operation?', ['An unlimited loop with no delay', 'A bounded retry count and a failure outcome', 'Ignoring every error'], 1,
    'Bound retries and define what happens when the operation still fails.'],
  ['functions', 'Functions & Contracts',
    'Functions package behavior behind parameters and return values. A clear contract describes accepted input, output and failure behavior. Small functions are easier to test than code mixing many side effects.',
    'Pure calculations can be checked independently of files or networks, making security assumptions easier to inspect.',
    'Python: def is_success(status): return 200 <= status < 300. JavaScript: const isSuccess = status => status >= 200 && status < 300.',
    ['Parameter', 'Return value', 'Contract', 'Pure function'],
    { instruction: 'Evaluate the isSuccess contract on paper for 199, 200, 299 and 300.', observation: 'The expected results are false, true, true and false. Boundary tests reveal off-by-one mistakes.' },
    'Which tests best check the boundaries of a 200..299 success range?', ['Only 250', 'Only 200', '199, 200, 299 and 300'], 2,
    'Test immediately inside and outside each boundary.'],
  ['modules', 'Modules & Dependencies',
    'Modules separate code into named units with explicit imports and exports. Dependencies bring reusable functionality but also add maintenance and supply-chain responsibilities.',
    'Small dependency surfaces and reproducible installs make behavior easier to review and reproduce.',
    'A parser module can return validated data while a storage module handles the filesystem. Neither should need terminal presentation logic.',
    ['Import', 'Export', 'Dependency', 'Lockfile'],
    { instruction: 'Split an imaginary notes program into parsing, storage and presentation modules. Write one responsibility for each.', observation: 'A parser can be tested without a real terminal, and presentation can change without rewriting storage.' },
    'What is a useful module boundary?', ['Put all code in the menu', 'Separate parsing from presentation and persistence', 'Make every function read global state'], 1,
    'Independent responsibilities allow focused tests and safer changes.'],
  ['files', 'Files, Paths & Encodings',
    'Programs read and write bytes through filesystem APIs. Text decoding gives those bytes meaning, often using UTF-8. Paths can be absolute or relative; user-controlled paths must stay within the intended scope.',
    'An unchecked path can reach unintended data. Writing directly over a file can also leave partial content after a failure.',
    'A notes application should restrict a requested filename to its own notes directory. A value such as ../private.txt changes the path scope.',
    ['UTF-8', 'Path traversal', 'Atomic replacement', 'Error handling'],
    { instruction: 'Classify notes.txt and ../private.txt against an application that accepts only plain filenames. Use paper; do not open real private files.', observation: 'The second value attempts to leave the expected directory and must be rejected by the filename contract.' },
    'Why validate a filename supplied by a user?', ['To prevent unintended path access', 'To change the CPU architecture', 'To avoid all future bugs'], 0,
    'Validate input and enforce a destination boundary before accessing the filesystem.'],
  ['json', 'JSON & Validation',
    'JSON represents objects, arrays, strings, numbers, booleans and null. Parsing checks JSON syntax, not whether the resulting value meets your application\'s requirements.',
    'Well-formed but unexpected data can still break assumptions. Validate required fields, types, ranges and unknown versions.',
    'The JSON {"score":"ten"} is syntactically valid, but a score field that requires an integer cannot accept it.',
    ['Serialization', 'Parsing', 'Schema', 'Range'],
    { instruction: 'Validate these synthetic scores on paper: 8, "8", -1 and 99, with a contract of integer 0 through 10.', observation: 'Only the numeric value 8 satisfies the stated contract without coercion.' },
    'What does successful JSON parsing establish?', ['Every required field exists', 'The application can trust all values', 'The input has valid JSON syntax'], 2,
    'After parsing, check the shape and meaning of the resulting value.'],
  ['errors', 'Errors & Debugging',
    'Errors should carry enough context for diagnosis without exposing secrets. Distinguish invalid input, missing resources and operational failures. Catch errors where you can respond meaningfully.',
    'Silently replacing every failure with success hides data loss. Raw stack traces can confuse users and expose internal details.',
    'A missing progress file can mean first use. A permission-denied error should explain the access problem instead of silently discarding saved progress.',
    ['Exception', 'Error code', 'Recovery', 'Diagnostic'],
    { instruction: 'Design user-facing messages for a missing optional file and an unreadable required file. State whether to continue.', observation: 'The missing optional file may use a default; the unreadable required file should not be overwritten.' },
    'How should an unreadable saved state be handled?', ['Overwrite it silently', 'Report the problem and preserve it', 'Pretend it was saved'], 1,
    'Preserve existing data and explain an actionable recovery path.'],
  ['http-apis', 'HTTP Requests & APIs',
    'An API defines how software interacts. HTTP clients send requests and interpret status, headers and bodies. Set timeouts, validate responses and consider whether retries could duplicate a write.',
    'Network calls can fail or return unexpected data. A successful transport operation does not guarantee an application-level success.',
    'A POST creating an order may succeed even if the response is lost. Retrying blindly can create a duplicate; an idempotency mechanism can prevent that.',
    ['API contract', 'Timeout', 'Status code', 'Idempotency'],
    { instruction: 'Design an offline mock response with status 200 and an invalid body. Decide which checks a client still needs.', observation: 'The client must validate the body schema even after receiving a success status.' },
    'Why be careful when retrying a POST after a timeout?', ['The first request may already have changed server state', 'Timeouts guarantee no server work happened', 'POST never changes anything'], 0,
    'An uncertain response does not prove failure; retries need a strategy for duplicate effects.'],
  ['automation', 'Python, JavaScript & Bash Automation',
    'Choose a language based on the task and environment. Python is useful for data processing, JavaScript integrates well with Node.js applications, and Bash composes local commands. All need validation, bounded work and documentation.',
    'Reliable automation has a defined scope, previewable effects and clear failure reporting. Understand a task before scaling it.',
    'For a log summarizer, parse synthetic lines, count events and print a report first. Add real file access only after reviewing paths and handling errors.',
    ['Scripting', 'Dry run', 'Testing', 'Documentation'],
    { instruction: 'Run a local JavaScript count of synthetic events. If Python is already installed, an equivalent is: python -c "print([200, 404, 500].count(404))".', commands: { all: 'node -p "[200,404,500].filter(code => code >= 400).length"' }, observation: 'JavaScript prints 2 because it counts all error statuses here; the Python example prints 1 because it counts only 404. Read the contract before comparing outputs.' },
    'What should precede automating a sensitive workflow?', ['Unlimited retries on production', 'Removing documentation', 'Understanding, testing and documenting its effects'], 2,
    'Build and verify the smallest safe workflow before automating it at scale.'],
]);
